version: 2
build:
  os: 'ubuntu-22.04'
  tools:
    nodejs: '16'
  commands:
    - npm install -g yarn
    - yarn
    - yarn build:storybook
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - ls packages/core/docs
    - cp -r packages/core/docs/* $READTHEDOCS_OUTPUT/html/
    - ls $READTHEDOCS_OUTPUT/html/
