version: 2
build:
  os: 'ubuntu-22.04'
  tools:
    nodejs: '16'
  commands:
    - npm install -g yarn
    - yarn 
    - yarn build:storybook
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r packages/core/docs $READTHEDOCS_OUTPUT/html/
