version: 2
build:
  os: 'ubuntu-22.04'
  tools:
    nodejs: '16'
  commands:
    - yarn install
    - npm build:storybook
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r packages/core/docs $READTHEDOCS_OUTPUT/html/
